CREATE TABLE TBCIDADE(
    CODIGO INTEGER NOT NULL,
    NOME VARCHAR(50),
    CONSTRAINT PK_CIDADE PRIMARY KEY (CODIGO)
);
create table TBFORNECEDOR(
   CODIGO INTEGER NOT NULL,
   NOMEFANTASIA VARCHAR(100),
   RAZAOSOCIAL VARCHAR(100),
   CNPJ VARCHAR(18),
   CEP INTEGER,
   CIDADE INTEGER,
   LOGRADOURO VARCHAR(50),
   COMPLEMENTO VARCHAR(50),
   BAIRRO VARCHAR(50),
   EMAIL VARCHAR(50),
   TELEFONEFIXO VARCHAR(20),
   TELEFONECELULAR VARCHAR(20),
   UF VARCHAR(2) NOT NULL,
   CONSTRAINT PK_FORNECEDOR PRIMARY KEY (CODIGO)
); 
create table TBPRODUTO (
  CODIGO INTEGER NOT NULL,
  PRODUTO VARCHAR(50),
  PRECO DECIMAL(10,2),
  UNIDADE varchar(10),
  ATIVO CHAR NOT NULL,
  CONSTRAINT PK_PRODUTO PRIMARY KEY (CODIGO)
 );
 create table TBSERVICO (
  CODIGO INTEGER NOT NULL,
  SERVICO VARCHAR (50),
  PRECO DECIMAL(10,2),
  CONSTRAINT PK_SERVICO PRIMARY KEY (CODIGO)
);
create table TBENTRADA (
  CODIGO INTEGER NOT NULL,
  QUANTIDADE INTEGER NOT NULL,
  VALOR DECIMAL(10,2),
  CODIGOFORNECEDOR INTEGER NOT NULL,
  DATA DATE NOT NULL,
  CONSTRAINT PK_ENTRADA PRIMARY KEY (CODIGO),
  FOREIGN KEY (CODIGOFORNECEDOR) REFERENCES TBFORNECEDOR(CODIGO)
);
CREATE TABLE ITEMENTRADA(
    CODIGO INTEGER NOT NULL,
    CODIGOENTRADA INTEGER NOT NULL,
    CODIGOPRODUTO INTEGER NOT NULL,
    QUANTIDADE INTEGER NOT NULL,
    CONSTRAINT PK_ITEMENTRADA PRIMARY KEY (CODIGO),
    FOREIGN KEY (CODIGOENTRADA) REFERENCES TBENTRADA(CODIGO),
    FOREIGN KEY (CODIGOPRODUTO) REFERENCES TBPRODUTO(CODIGO)
);
CREATE TABLE TBCLIENTE(
    CODIGO INTEGER NOT NULL,
    FISICO INTEGER,
    JURIDICO INTEGER,
    CEP INTEGER,
    CIDADE VARCHAR(100) NOT NULL,
    UF VARCHAR(2) NOT NULL,
    LAGRADOURO VARCHAR(50) NOT NULL,
    COMPLEMENTO VARCHAR(50),
    BAIRRO VARCHAR(50) NOT NULL,
    TELEFONEFIXO VARCHAR(20),
    TELEFONECELULAR VARCHAR(20),
    EMAIL VARCHAR(100),
    CONSTRAINT PK_CLIENTE PRIMARY KEY (CODIGO)
);
CREATE TABLE TBCLIENTEFISICO(
    CODIGOCLIENTE INTEGER NOT NULL,
    NOME VARCHAR(100),
    CPF VARCHAR(15),
    FOREIGN KEY (CODIGOCLIENTE) REFERENCES TBCLIENTE(CODIGO)
);
CREATE TABLE TBCLIENTEJURIDICO(
    CODIGOCLIENTE INTEGER NOT NULL,
    RAZAOSOCIAL VARCHAR(50),
    NOME VARCHAR(50),
    CNPJ VARCHAR(18),
    FOREIGN KEY (CODIGOCLIENTE) REFERENCES TBCLIENTE(CODIGO)
);
create table TBORDEMSERVICO(
  CODIGO INTEGER NOT NULL,
  CODIGOCLIENTE INTEGER NOT NULL,
  DATA date NOT NULL,
  TOTAL INTEGER NOT NULL,
  CONSTRAINT PK_ORDEMSERVICO PRIMARY KEY (CODIGO),
  FOREIGN KEY (CODIGOCLIENTE) REFERENCES TBCLIENTE(CODIGO)
);
CREATE TABLE TBITEMORDEMSERVICO (
    CODIGO INTEGER NOT NULL,
    TIPO CHAR NOT NULL,
    CODIGOPRODUTO INTEGER,
    CODIGOSERVICO INTEGER,
    QUANTIDADE INTEGER NOT NULL,
    CONSTRAINT PK_ITEMORDEMSERVICO PRIMARY KEY (CODIGO),
    FOREIGN KEY (CODIGOPRODUTO) REFERENCES TBPRODUTO(CODIGO),
    FOREIGN KEY (CODIGOSERVICO) REFERENCES TBSERVICO(CODIGO)
);
CREATE TABLE TBESTOQUE(
    CODIGO INTEGER NOT NULL,
    QUANTIDADEITENS INTEGER,
    CONSTRAINT PK_ESTOQUE PRIMARY KEY (CODIGO)
    
);
CREATE TABLE TBITEMESTOQUE(
    CODIGOESTOQUE INTEGER NOT NULL,
    CIDIGOPRODUTO INTEGER,
    QUANTIDADE INTEGER,
    FOREIGN KEY (CODIGOESTOQUE) REFERENCES TBESTOQUE(CODIGO),
    FOREIGN KEY (CIDIGOPRODUTO) REFERENCES TBPRODUTO(CODIGO)
);
create table TBOPERADOR (
   CODIGO INTEGER NOT NULL,
   NOME VARCHAR(100),
   CPF VARCHAR(15),
   FUNCAO VARCHAR(50),
   CEP INTEGER,
   CIDADE INTEGER,
   UF VARCHAR(2),
   LOGRADOURO VARCHAR(50),
   COMPLEMENTO VARCHAR(50),
   BAIRRO VARCHAR(50),
   EMAIL VARCHAR(50),
   TELEFONEFIXO VARCHAR(20),
   TELEFONECELULAR VARCHAR(20),
   CONSTRAINT PK_OPERADOR PRIMARY KEY (CODIGO)
 ); 
 CREATE TABLE TBFUNCAO(
    CODIGO INTEGER NOT NULL,
    TELA VARCHAR(50),
    CONSTRAINT PK_FUNCAO PRIMARY KEY (CODIGO)
);
 CREATE TABLE TBPERMISSAO(
    CODIGOOPERADOR INTEGER NOT NULL,
    CODIGOFUNCAO INTEGER NOT NULL,
    FOREIGN KEY (CODIGOOPERADOR) REFERENCES TBOPERADOR(CODIGO),
    FOREIGN KEY (CODIGOFUNCAO) REFERENCES TBFUNCAO(CODIGO)
);


  
  